alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: telegram
      group_by: ['alertname','namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
      - matchers:
        - alertname = "Watchdog"
        receiver: "null"
      - matchers:
        - severity = "info"
        receiver: "null"
grafana:
  adminUser: admin
  adminPassword: prom-operator
  assertNoLeakedSecrets: false
  grafana.ini:
    server:
      root_url: http://localhost:3000/grafana
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: user@gmail.com
      password: pass
      skip_verify: true
  ingress:
    enabled: true
    hosts:
    - grafana.mtahatavaci.site
    path: /grafana/?(.*)
    pathType: ImplementationSpecific
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.mtahatavaci.site
  sidecar:
    dashboards:
      enabled: true
      multicluster:
        global:
          enabled: true
        etcd:
          enabled: true
  plugins:
  - digrich-bubblechart-panel
  - grafana-clock-panel
  - grafana-piechart-panel
prometheus:
  enabled: true

